int _putchar(char c);
void print-alphabet(void);
void print-alphabet_x10(void);
int _islower(int c);
in _isalpha(int c);
int print_sign(int n);
int _abs(int);
int print_last_digit(int);
void jack-bauer(void);
void times_table(void);
int add(int, int);
void print_to_98(int n);
void print_times-table(int n);
